version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/civall-website-cms:cached
    command: sleep infinity
    network_mode: host
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: civall
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: civall
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: